version: '3.8'

services:
  python-app:
    image: ${REGISTRY}/${REPO}:latest  # 使用推送到阿里云的镜像
    working_dir: /tikeAgent
    volumes:
      - .env:/tikeAgent/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/tikeAgent
      - ENV_FILE=/tikeAgent/.env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - tike-agent-net
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tike-agent-net

networks:
  tike-agent-net:
    driver: bridge

volumes:
  redis_data:
