version: '3.8'

services:
  python-app:
    image: registry.cn-hangzhou.aliyuncs.com/sinrpc/ai-wallet:latest  # 使用阿里云镜像
    working_dir: /tikeAgent
    volumes:
      - .env:/tikeAgent/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/tikeAgent
      - ENV_FILE=/tikeAgent/.env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=I5xlwT2025
      - MYSQL_DB=ai_wallet_db
    networks:
      - tike-agent-net
    depends_on:
      - redis
      - pgsql
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - tike-agent-net

  pgsql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - tike-agent-net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: I5xlwT2025
      MYSQL_DATABASE: ai_wallet_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - tike-agent-net

networks:
  tike-agent-net:
    driver: bridge
