version: '3.8'

services:
  python-app:
    image: registry.cn-hangzhou.aliyuncs.com/sinrpc/ai-wallet:latest  # 使用推送到阿里云的镜像
    working_dir: /tikeAgent
    volumes:
      - .env:/tikeAgent/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/tikeAgent
      - ENV_FILE=/tikeAgent/.env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - tike-agent-net
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data  # 将本地 ./redis/data 挂载到 redis 容器的 /data 目录
    networks:
      - tike-agent-net

networks:
  tike-agent-net:
    driver: bridge

volumes:
  redis_data:  # 如果您不希望使用数据卷，可以删除这个定义
