version: '3.8'

services:
  python-app:
    image: registry.cn-hangzhou.aliyuncs.com/sinrpc/ai-wallet:latest  # 使用推送到阿里云的镜像
    working_dir: /tikeAgent
    volumes:
      - .env:/tikeAgent/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/tikeAgent
      - ENV_FILE=/tikeAgent/.env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ai_wallet_db
    network_mode: host  # 使用宿主机的网络
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data  # 将宿主机的 ./redis/data 目录挂载到容器的 /data 目录
    network_mode: host  # 使用宿主机的网络

  mysql:
    image: mysql:5.7  # 使用 MySQL 8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_wallet_db
      MYSQL_USER: ai_wallet
      MYSQL_PASSWORD: ai_wallet_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data  # 将宿主机的 ./data 目录挂载到容器的 /data 目录
      - mysql_data:/var/lib/mysql  # 持久化 MySQL 数据库文件
    network_mode: host  # 使用宿主机的网络
    command: >
      bash -c "docker-entrypoint.sh --skip-grant-tables & 
      sleep 10; 
      mysql -u root -proot -e \"ALTER USER 'ai_wallet'@'%' IDENTIFIED WITH mysql_native_password BY 'ai_wallet_password';\"; 
      wait"

volumes:
  redis_data:
  mysql_data:
